# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
use_frameworks!
target 'LeagueMobileChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.6.0'

  # Pods for LeagueMobileChallenge

  target 'LeagueMobileChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeagueMobileChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
